### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by nwoeanhinnogaehr** [thecodeboss/AcousticSimulator#15]
Please consider adding a license to the project so that others are permited to use it. You can easily do so by clicking this link: https://github.com/thecodeboss/AcousticSimulator/community/license/new?branch=master

Thank you!

**Comment by thecodeboss** [comment]
@nwoeanhinnogaehr thanks for the suggestion, I added an MIT license to the project. If you're planning to use it, definitely let me know how it goes.
